esphome:
  name: "esp32-smart-doorbell"
  friendly_name: Smart Doorbell
  min_version: 2026.04.0
  name_add_mac_suffix: false
  project:
    name: zuidwijk.esphome-doorbell
    version: "3.0"

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption: 
    key: !secret api_doorbell

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: !secret ota_password_doorbell

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

# https://github.com/esphome/bluetooth-proxies/blob/main/esp32-generic/esp32-generic.yaml
#esp32_ble_tracker:
  #scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    #active: true
bluetooth_proxy:
  active: true

time:
  - platform: homeassistant
    id: homeassistant_time
 
text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"
 
sensor:
  - platform: uptime
    name: "Uptime"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
 
globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: 'true'
 
switch:
  - platform: gpio
    pin:
      number: GPIO5
      inverted: false
    name: "Relay"
    id: relay
    internal: true
    icon: mdi:alarm-bell
  - platform: restart
    name: "Restart"
  - platform: template
    name: "Chime Active"
    id: chime_active
    restore_mode: disabled
    turn_on_action:
      - globals.set:
          id: chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: chime
          value: 'false'
    lambda: |-
      return id(chime);
     
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "Outside Switch"
    filters:
      # Small filter, to debounce the button press.
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      # Only turn on the chime when it is active.
      then:
        if:
          condition:
            - switch.is_on: chime_active
          then:
            - switch.turn_on: relay
    on_release:
      # On release, turn of the chime.
      - switch.turn_off: relay        
 
  - platform: status
    name: "Status"

button:
- platform: template
  name: "Ring"
  id: ring_button
  icon: mdi:bell-ring
  on_press:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay
